/**
 * Recommendation generated by the Organization Agent
 */
export interface Recommendation {
  id: string;
  noteId: string;
  action: RecommendationAction;
  confidence: number;
  reasoning: string;
  impact: ImpactLevel;
  reversible: boolean;
  relatedNotes?: string[]; // For merge recommendations
  suggestedTitle?: string;
  suggestedFolder?: string;
  timestamp: Date;
}

/**
 * Types of actions that can be recommended
 */
export enum RecommendationAction {
  KEEP = 'keep',
  REVIEW = 'review',
  ARCHIVE = 'archive',
  DELETE = 'delete',
  MERGE_DUPLICATES = 'merge_duplicates',
  RENAME = 'rename'
}

/**
 * Impact level of a recommendation
 */
export enum ImpactLevel {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high'
}

/**
 * Status of a recommendation
 */
export enum RecommendationStatus {
  PENDING = 'pending',
  APPROVED = 'approved',
  REJECTED = 'rejected',
  EXECUTED = 'executed'
}